### ISSUE TITLE
Updated build

### ISSUE THREAD

**Issue by nazwa** [ljsabc/Code-OSS-Win32-arm64#2]
Hi @ljsabc!

Amazing work with the build - it seems to work flawlesly.

Is there any chance you could build it again with a more recent version of VSCode? 
The current version of Remote-WSL with support for ARM needs at least v40 of vscode.

Thank you so much!

**Comment by ljsabc** [comment]
This repo is more like a tutorial to show a proof that code-OSS can be built on ARM64 devices.
Anyway, I will try to have a more recent build but since I have sold my Huawei tablet and Surface Pro X is currently still not available, don't expect the update will come out really soon. Sorry for that.

**Comment by nazwa** [comment]
Thanks for the update! I was actually able to get quite far following your instrutions and the official How to contribute guide and _a lot_ of trial and error.

The easiest way I found to get the more recent version to work is by replacing the officially installed electron files with yours & combining it with manually compiled .node extensions (following the contribute guide). That way VSCode seems to thinks it's actually official to some extent.

![image](https://user-images.githubusercontent.com/4353913/71629889-dfcea600-2bf7-11ea-93a8-02b331f5de00.png)

Of course my excitement was quickly ruined by finding out that the `remote-wsl` extension doesn't actually work with OSS version of VSCode! How annoying is that?! 

So for all those wishing to use the Surface Pro X with WSL2 - seems like we need to wait for the official arm64 release. Shame!

**Comment by ljsabc** [comment]
> Thanks for the update! I was actually able to get quite far following your instrutions and the official How to contribute guide and _a lot_ of trial and error.
> 
> The easiest way I found to get the more recent version to work is by replacing the officially installed electron files with yours & combining it with manually compiled .node extensions (following the contribute guide). That way VSCode seems to thinks it's actually official to some extent.
> 
> ![image](https://user-images.githubusercontent.com/4353913/71629889-dfcea600-2bf7-11ea-93a8-02b331f5de00.png)
> 
> Of course my excitement was quickly ruined by finding out that the `remote-wsl` extension doesn't actually work with OSS version of VSCode! How annoying is that?!
> 
> So for all those wishing to use the Surface Pro X with WSL2 - seems like we need to wait for the official arm64 release. Shame!

That's true. I cannot run the WSL tool either.
